{
	"*": {
	
		"*": {
			"text": {
				"size": "14"
			}
		},
	
		// components		
		"page": {
			
		},
		
		"break": {
			"size": { "height": 1 }
		},
		
		// miscellaneous
		"visible": { 
			"visible": "true" 
		},
		"invisible": { 
			"visible": "false" 
		},
		"centered": {
			"align": "center"
		},
				
		// miscellaneous
		"rounded": {
			"border": {
				"radius": "12"
			}
		},
		"circle": {
			"border": {
				"radius": "50%"
			}
		}
		
	}
}